// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSdkLibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Represents the last move data made by an actor within the Tic Tac Toe
    /// game from which the AI can update the game state and respond with its
    /// next move.
    /// </summary>
    public partial class ExecuteMoveRequest
    {
        /// <summary>
        /// Initializes a new instance of the ExecuteMoveRequest class.
        /// </summary>
        public ExecuteMoveRequest() { }

        /// <summary>
        /// Initializes a new instance of the ExecuteMoveRequest class.
        /// </summary>
        public ExecuteMoveRequest(string azurePlayerSymbol, string humanPlayerSymbol, IList<string> gameBoard, int? move = default(int?))
        {
            Move = move;
            AzurePlayerSymbol = azurePlayerSymbol;
            HumanPlayerSymbol = humanPlayerSymbol;
            GameBoard = gameBoard;
        }

        /// <summary>
        /// Indicates the position on the board the last actor to update state
        /// chooses.
        /// This is a Nullable type because, if it were not, the value would
        /// default to 0 if it was not present in the request body.
        /// The move field is not required if and only if the game board is
        /// empty (contains only ? symbols)
        /// </summary>
        [JsonProperty(PropertyName = "move")]
        public int? Move { get; set; }

        /// <summary>
        /// The letter X or the letter O indicating the symbol used by Azure.
        /// </summary>
        [JsonProperty(PropertyName = "azurePlayerSymbol")]
        public string AzurePlayerSymbol { get; set; }

        /// <summary>
        /// The letter X or the letter O indicating the symbol used by the
        /// human.
        /// </summary>
        [JsonProperty(PropertyName = "humanPlayerSymbol")]
        public string HumanPlayerSymbol { get; set; }

        /// <summary>
        /// An array of X, O, and ? symbols representing the current state of
        /// the game board where ? is an open space and the other symbols
        /// correspond to players.
        /// </summary>
        [JsonProperty(PropertyName = "gameBoard")]
        public IList<string> GameBoard { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (AzurePlayerSymbol == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AzurePlayerSymbol");
            }
            if (HumanPlayerSymbol == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "HumanPlayerSymbol");
            }
            if (GameBoard == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "GameBoard");
            }
            if (this.Move > 8)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Move", 8);
            }
            if (this.Move < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Move", 0);
            }
            if (this.AzurePlayerSymbol != null)
            {
                if (this.AzurePlayerSymbol.Length > 1)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "AzurePlayerSymbol", 1);
                }
                if (this.AzurePlayerSymbol.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "AzurePlayerSymbol", 0);
                }
                if (!System.Text.RegularExpressions.Regex.IsMatch(this.AzurePlayerSymbol, "X|O"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "AzurePlayerSymbol", "X|O");
                }
            }
            if (this.HumanPlayerSymbol != null)
            {
                if (this.HumanPlayerSymbol.Length > 1)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "HumanPlayerSymbol", 1);
                }
                if (this.HumanPlayerSymbol.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "HumanPlayerSymbol", 0);
                }
                if (!System.Text.RegularExpressions.Regex.IsMatch(this.HumanPlayerSymbol, "X|O"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "HumanPlayerSymbol", "X|O");
                }
            }
            if (this.GameBoard != null)
            {
                if (this.GameBoard.Count > 9)
                {
                    throw new ValidationException(ValidationRules.MaxItems, "GameBoard", 9);
                }
                if (this.GameBoard.Count < 9)
                {
                    throw new ValidationException(ValidationRules.MinItems, "GameBoard", 9);
                }
            }
        }
    }
}
